
$B2B_API_URI = ENV['B2B_API_URI'] || 'http://localhost:5001'
$B2B_PROCESSOR_URI = ENV['$B2B_PROCESSOR_URI'] || 'http://localhost:5002'
$BANKRUPTCY_REGISTRATION_URI = ENV['$BANKRUPTCY_REGISTRATION_URI'] || 'http://localhost:5004'
$CASEWORK_API_URI = ENV['$CASEWORK_API_URI'] || 'http://localhost:5006'
$LEGACY_DB_URI = ENV['$LEGACY_DB_URI'] || 'http://localhost:5007'
$MIGRATOR_URI = ENV['MIGRATOR_URI'] || 'http://localhost:5009'
$FRONTEND_URI = ENV['$FRONTEND_URI'] || 'http://localhost:5010'
$NAMES_SEARCH_URI = ENV['$NAMES_SEARCH_URI'] || 'http://localhost:5013'

$POSTGRES_HOST = ENV['POSTGRES_HOST'] || 'localhost'
$POSTGRES_PORT = ENV['POSTGRES_PORT'] || '5432'
$POSTGRES_USER = ENV['POSTGRES_USER'] || 'landcharges'
$POSTGRES_PASSWORD = ENV['POSTGRES_PASSWORD'] || 'lcalpha'
